apiVersion: v1
kind: Service
metadata:
  name: nd-service
spec:
  type: NodePort
  selector:
    app: nd
  ports:
    - port: 80          # Port exposed by the service
      targetPort: 3000  # Port your Node.js app listens on inside the container
      nodePort: 30080   # External port on the node (between 30000-32767)
